apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-lab1
  namespace: processing
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: fabianomorais/spok:1.0.0 # aqui passamos a imagem que foi desenvolvida por mim.
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/spark-app1.py"
  sparkVersion: 3.5.3
  timeToLiveSeconds: 30
  driver:
    cores: 1
    memory: 500m
    serviceAccount: spark-operator-spark
  executor:
    instances: 2
    cores: 1
    memory: 1024m
  