apiVersion: v1
kind: Secret
metadata:
  name: git-creds
data:
  known_hosts: Z2l0aHViLmNvbSBzc2gtZWQyNTUxOSBBQUFBQzNOodWIuY29tIHNzaC1yc2EgQUFBQUIzTnphQzF5YzJFQUFBQURBUUFCQ
  ssh: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tbgpOaEFBQUFBd0VBQVFBQUFZRUF3aFJ0QzNSOTBYQ2IzUy9COFF
